HOMEWORK 3
================
aw3253

Preparing to load and tidy data:

``` r
library(tidyverse)
```

## Problem 1

``` r
library(p8105.datasets)
data("instacart")

instacart
```

    ## # A tibble: 1,384,617 x 15
    ##    order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##       <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ##  1        1      49302                 1         1  112108 train               4
    ##  2        1      11109                 2         1  112108 train               4
    ##  3        1      10246                 3         0  112108 train               4
    ##  4        1      49683                 4         0  112108 train               4
    ##  5        1      43633                 5         1  112108 train               4
    ##  6        1      13176                 6         0  112108 train               4
    ##  7        1      47209                 7         0  112108 train               4
    ##  8        1      22035                 8         1  112108 train               4
    ##  9       36      39612                 1         0   79431 train              23
    ## 10       36      19660                 2         1   79431 train              23
    ## # ... with 1,384,607 more rows, and 8 more variables: order_dow <int>,
    ## #   order_hour_of_day <int>, days_since_prior_order <int>, product_name <chr>,
    ## #   aisle_id <int>, department_id <int>, aisle <chr>, department <chr>

This data set has 15 variables collected from 1,384,617 products ordered
on instacart.Some key variables are the product name, and where this
product is located like the aisle,aisle\_id, and department name. We
also get some important information about the user that describes days
since the last order to see how often a user orders from instacart or if
they are a first-time user. For example, while user\_id \#112108 placed
their last order 9 days ago, user\_id \#167740 placed their last order 2
days ago.

``` r
uniq_aisles = distinct(instacart, aisle_id)

aisle_count <- instacart %>%
  group_by(aisle_id) %>%
  summarize(n = n()) %>%
  arrange(desc(aisle_id))
```

There are 134 aisles, and it seems that the aisle most ordered from is
aisle 83, fresh vegetables.

``` r
which_aisles = 
  instacart %>%
  group_by(aisle_id) %>%
  summarize(n = n()) %>%
  filter(n > 100000)

which_aisles
```

    ## # A tibble: 2 x 2
    ##   aisle_id      n
    ##      <int>  <int>
    ## 1       24 150473
    ## 2       83 150609

``` r
  ggplot(which_aisles, aes(x = aisle_id)) + 
  geom_histogram()+
   ggtitle("Figure 3: Number of orders in Aisles 24 and 83")
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

![](p8105_hw3_aw3253_files/figure-gfm/aisle%20plot-1.png)<!-- -->

Aisles are ordered from least to greatest on the histogram, and only 2
aisles, fresh fruits and fresh vegetables had over 10,000 orders.

``` r
pop_data =
  instacart%>% 
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>% 
  group_by(aisle, product_name) %>% 
  summarize(n = n()) %>% 
  filter(n == max(n))
```

    ## `summarise()` has grouped output by 'aisle'. You can override using the `.groups` argument.

``` r
pop_data
```

    ## # A tibble: 3 x 3
    ## # Groups:   aisle [3]
    ##   aisle                      product_name                                      n
    ##   <chr>                      <chr>                                         <int>
    ## 1 baking ingredients         Light Brown Sugar                               499
    ## 2 dog food care              Snack Sticks Chicken & Rice Recipe Dog Treats    30
    ## 3 packaged vegetables fruits Organic Baby Spinach                           9784

Light brown sugar is ordered the most in baking ingredients (499
orders), Snack Sticks Chicken & Rice Recipe Dog Treats is he popular
product in the dog care aisle (30 orders), and organic baby spinach is
the most popular i the packed vegetable fruits aisle (9784 orders).

``` r
sweets = 
instacart %>% 
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>% 
  group_by(product_name, order_dow) %>% 
  summarize(avg_hour = mean(order_hour_of_day))
```

    ## `summarise()` has grouped output by 'product_name'. You can override using the `.groups` argument.

``` r
sweets_final=
  pivot_wider(
    sweets, 
    names_from = "product_name", 
    values_from = "avg_hour")

sweets_final
```

    ## # A tibble: 7 x 3
    ##   order_dow `Coffee Ice Cream` `Pink Lady Apples`
    ##       <int>              <dbl>              <dbl>
    ## 1         0               13.8               13.4
    ## 2         1               14.3               11.4
    ## 3         2               15.4               11.7
    ## 4         3               15.3               14.2
    ## 5         4               15.2               11.6
    ## 6         5               12.3               12.8
    ## 7         6               13.8               11.9

On average, orders for Pink Lady Apples and Coffee Ice Cream are made
between the 11th to 14th hour of the day.
